export { default as authRouter } from './auth/auth.routes'
export { default as courseRouter } from './course/course.routes'
export { default as uploadRouter } from './upload'
export { default as userCourseRouter } from './user-course/user-course.routes'
export { default as userRouter } from './user/user.routes'
